name: Actualizador Automático Flow
on:
  schedule:
    - cron: '0 * * * *'  # Se ejecuta solo cada 1 hora
  workflow_dispatch:      # Permite ejecutarlo a mano para probar

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar Extractor
        env:
          USER: ${{ secrets.FLOW_USER }}
          PASS: ${{ secrets.FLOW_PASSWORD }}
        run: python extractor.py

      - name: Publicar lista actualizada
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
